version: '3.4'
services:
  manager:
    build: manager
    networks:
    - main
    depends_on:
    - weaviate
  api:
    build: api
    ports:
    - 8000:8000
    networks:
    - main
    environment:
    - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
    - weaviate
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.22.1
    #ports:
    #- 8080:8080
    #- 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    networks:
    - main
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
networks:
  main:
volumes:
  weaviate_data:
